name: For CLs coming from trusted partners, Auto run tests and mark ready for pull.
on:
  pull_request:

jobs:
  auto-assign-intel:
    runs-on: ubuntu-latest
    if: |
      github.event.sender.type == 'User' ||
      endsWith(github.event.sender.login, 'web')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create a new Github Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./.github/workflows/trusted_partners.js')
            console.log(await script.intel({github, context}))
            
