name: For CLs coming from trusted partners, Auto run tests and mark ready for pull.
on:
  pull_request:
    branches:
      - main
jobs:
  auto-assign-intel:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false &&
      github.event.sender.type == 'User' &&
      endsWith(github.event.sender.email, '@sampathweb.com')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create a new Github Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./.github/workflows/trusted_partners.js')
            console.log(await script.intel({github, context}))
            
