name: For CLs coming from trusted partners, Auto run tests and mark ready for pull.
on:
  pull_request:
    branches:
      - main
jobs:
  auto-assign-intel:
    runs-on: ubuntu-latest
    permissions:
      # Needed to attach tags into the PR
      contents: write
    if: |
      github.event.pull_request.draft == false &&
      github.event.sender.type == 'User'
    steps:
      - name: Print Variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo ${{github.event.sender.type}}
          echo ${{github.event.sender.email}}
          echo ${{github.event.sender}}
          echo ${{github.event.pull_request}}
          echo "$GITHUB_CONTEXT"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create a new Github Issue
        uses: actions/github-script@v5
        env:
          USER: ${{github.event.sender.email}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./.github/workflows/trusted_partners.js');
            console.log(context);
            const username = context.payload.pull_request.user.login;
            console.log(username);
            const domain = await script.get_email_domain({github, username});
            // TODO - Remove after test
            console.log(username);
            if (username == "sampathweb")
              console.log(await script.intel({github, context}));
            switch(domain) {
            case "intel.com":
              console.log(await script.intel({github, context}));
              break;
            case "sampathweb.com":
              console.log("Sampathweb. No action necessary");
              break;
            case "google.com":
              console.log("Googler. No action necessary");
              break;
            default:
              console.log("Skip Trusted Partner Action");
            }
