name: For CLs coming from trusted partners, Auto run tests and mark ready for pull.
on:
  pull_request_target:
    branches:
      - main
jobs:
  auto-assign-intel:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false &&
      github.event.sender.type == 'User'
    steps:
      - name: Print Variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo ${{github.event.sender.type}}
          echo ${{github.event.sender.email}}
          echo ${{github.event.sender}}
          echo ${{github.event.pull_request}}
          echo "$GITHUB_CONTEXT"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create a new Github Issue
        uses: actions/github-script@v6
        env:
          USER: ${{github.event.sender.email}}
        with:
          github-token: ${{secrets.GH_TEST_ACTION}}
          script: |
            const script = require('./.github/workflows/trusted_partners.js');
            console.log(context);
            const username = context.payload.pull_request.user.login;
            console.log(username);
            // const domain = await script.get_email_domain({github, username});
            console.log(await script.intel({github, context}));
            // TODO - Remove after test
