# This is a basic workflow that is manually triggered

name: Create Issue on TF PR Rollback

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ROLLBACK_PR=')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create a new Github Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const rollback_commit = context.payload.head_commit.id
            const pr_number = context.payload.head_commit.message.match(/\[ROLLBACK_PR=(\d+).*/)[1]
            const owner = context.payload.repository.owner.name
            const repo = context.payload.repository.name
            console.log(context.payload.repository.owner)
            console.log(`Original PR: ${pr_number} and Rollback Commit: ${rollback_commit}`)
            // Get the Original PR Details
            const pr_resp = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: parseInt(pr_number)
            })
            if (pr_resp.status != 200 || pr_resp.data.state != 'closed') {
              console.log("PR doesn't exist or not closed.  Not a valid condition.")
              console.log(pr_resp)
            }
            const pr_title = pr_resp.data.title
            let assignees = pr_resp.data.assignees
            assignees.push(pr_resp.data.user.login)
            console.log(assignees, pr_number, pr_title)
            // Create an new GH Issue and reference the Original PR
            const resp = await github.rest.issues.create({
              owner,
              repo,
              assignees,             
              title: `Creating Issue for Rollback of #${pr_number}: ${pr_title}`,
              body: `Merged PR #${pr_number} is rolled back in ${rollback_commit}.  
              Please follow up with reviewer and close this issue once its resolved.`
            })
            console.log(resp)
