# This is a basic workflow that is manually triggered

name: Create Issue on TF PR Rollback

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'sampathweb/test-gh-actions' &&
      contains(github.event.head_commit.message, 'Rollback of PR #')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create a new Github Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./.github/workflows/create_issue.js')
            console.log(await script({github, context}))
