# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
      - main

jobs:
  get-pr:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ROLLBACK_PR=')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get PR and assignee information
        run: |
          echo '::set-output name=assignees::sampathweb'
          cat <<< "${{ github.event.head_commit.message }}" > message.txt
          echo '::set-output name=PR_NUMBER::$(cat message.txt | tr "\n" " " | sed -rn "s/.*ROLLBACK_PR=([^]]+).*/\1/p")'
        id: pr-data
      - name: Echo PR Data Outputs
        run: |
          echo PR ${{ steps.pr-data.outputs.PR_NUMBER }}
          echo Assignee ${{ steps.pr-data.outputs.assignees }}
      - name: Create a new Github Issue
        uses: actions/github-script@v4
        env:
          PR_NUMBER: ${{ steps.pr-data.outputs.PR_NUMBER }}
          ROLLBACK_COMMIT: ${{ github.event.head_commit.id }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {PR_NUMBER, ROLLBACK_COMMIT} = process.env
            console.log("Commit Message")
            console.log(github.event.head_commit.message)
            let pr_number = github.event.head_commit.message.match("s/.*ROLLBACK_PR=([^]]+).*/g)[0];
            console.log(`Hello ${pr_number} ${ROLLBACK_COMMIT}`)
            const result = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Creating Issue for Rollback of #${pr_number}`
              body: `PR #${pr_number} is Rolled back in ${ROLLBACK_COMMIT}.  Please follow up.`
            })
            console.log(result)

