# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[ROLLBACK_PR=')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get PR and assignee information
        run: |
          echo '::set-output name=assignees::sampathweb'
          echo "::set-output name=ip-address::$(curl -s ifconfig.me)"
          echo '::set-output name=PR_NUMBER2::$(sed -rn "s/.*ROLLBACK_PR=([^]]+).*/\1/p" <<<"Test [ROLLBACK_PR=3333]adfadf")'
          echo '::set-output name=PR_NUMBER3::$(echo 1234)'
          PR_NUMBER1=$(sed -rn "s/.*ROLLBACK_PR=([^]]+).*/\1/p" <<<"Test [ROLLBACK_PR=3333]adfadf")
          echo 'PR_NUMBER=$(sed -rn "s/.*ROLLBACK_PR=([^]]+).*/\1/p" <<<"Test [ROLLBACK_PR=1234]adfadf")'
        id: pr-data
      - run: |
          echo PR ${{ env.PR_NUMBER }}
          echo PR1 ${{ env.PR_NUMBER1 }}
          echo PR2 ${{ teps.pr-data.outputs.PR_NUMBER2 }}
          echo PR3 ${{ teps.pr-data.outputs.PR_NUMBER3 }}
          echo Assignee ${{ steps.pr-data.outputs.assignees }}
          echo IP Address ${{ steps.pr-data.outputs.ip-address }}

      - name: Create GitHub Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROLLBACK_COMMIT: ${{ github.event.head_commit.id }}
        with:
          filename: .github/issue-template.md
          assignees: ${{ steps.pr-data.outputs.assignees }}
        id: create-issue
      - run: |
          echo "${{toJSON(github.event)}}"
          echo Created issue number ${{ steps.create-issue.outputs.number }}
          echo Created ${{ steps.create-issue.outputs.url }}
          echo PR2 ${{ teps.pr-data.outputs.PR_NUMBER2 }}
          echo PR3 ${{ teps.pr-data.outputs.PR_NUMBER3 }}
          echo Assignee ${{ steps.pr-data.outputs.assignees }}
          echo IP Address ${{ steps.pr-data.outputs.ip-address }}
